apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-nginx
  name: demo-nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/e2e-az-name
                operator: In
                values:
                - e2e-az1
                - e2e-az2
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: another-node-label-key
                operator: In
                values:
                - another-node-label-value
      containers:
      - command:
        - sh
        - -c
        - sleep 36000000000
        image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt
          name: cache-volume
        - mountPath: /tmp/nfs
          name: nfs-test
      - command:
        - sh
        - -c
        - sleep 36000000000
        image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 270Mi
          requests:
            cpu: 100m
            memory: 70Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: config-volume
          subPath: etc/nginx/nginx.conf
        - mountPath: /mnt/
          name: config-volume-non-subpath
        - mountPath: /tmp/1
          name: test-hostpath
        - mountPath: /tmp/2
          name: cache-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - echo "InitContainer" >> /tmp/nfs/init
        image: nginx
        imagePullPolicy: IfNotPresent
        name: init1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/nfs
          name: nfs-test
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: master-test
        operator: Equal
        value: test
      - effect: NoExecute
        key: master-test
        operator: Equal
        tolerationSeconds: 60
        value: test
      volumes:
      - hostPath:
          path: /etc/hosts
          type: File
        name: test-hostpath
      - configMap:
          defaultMode: 420
          items:
          - key: nginx.conf
            path: etc/nginx/nginx.conf
          name: nginx-conf
        name: config-volume
      - configMap:
          defaultMode: 420
          name: nginx-conf
        name: config-volume-non-subpath
      - emptyDir:
          medium: Memory
        name: cache-volume
      - name: nfs-test
        nfs:
          path: /data/k8s-data/testDir
          server: 192.168.10.12